### ISSUE TITLE
Create droplet and set it up

### ISSUE THREAD

**Issue by cavillo** [cavillo/band-bmb-project#2]
- Start a new droplet in Digital Ocean:
  - NYC2
  - 16GB / 4 AMD CPU
  - 200 GB / 8 TB
  - $84/mo

- install all dependencies and update package
- install docker and docker compose
- set up firewall and port security

![Image](https://github.com/user-attachments/assets/c1156fee-0c50-4bc6-afe2-9f68243cde2e)

**Comment by victorgmp** [comment]
Drolet create, package updated and users created, but I select the wrong plan, then the server specs will be updated.

**Comment by victorgmp** [comment]
New drolet was create with the rigth specs

**Comment by victorgmp** [comment]
docker and docker compose was installed

**Comment by victorgmp** [comment]
firewall setup is complete!

**Comment by victorgmp** [comment]
node 20.17.0 and 22.7.0 was installed
